# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WahwO2UwpimUM4F3-_qxy7oibqQCnBb_
"""

import numpy as np
arr1=np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end='\n\n')

arr2=np.array([[1,2,3],[4,5,6]])
print("2-dim",arr2,sep='\n',end='\n\n')

arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("multi-dim",arr3,sep='\n',end='\n\n')

zeros = np.zeros((3,4))
print(zeros)
ones = np.ones((3,4))
print(ones)
identity = np.eye(4)
print(identity)
full_array = np.full((10, 2), 'Booked')
print(full_array)

range_arr= np.arange(10,0,-1)
print(range_arr)

lin_space = np.linspace(50, 100, 6)
print(lin_space)

np.random.seed(10)
rand_arr=np.random.randint(100)
print(rand_arr)

rand_int = np.random.randint(30,60)
print(rand_int)

rand_float = np.random.rand(3,2)
print(rand_float)

rand_int = np.random.randint(1,6, (3,3))
print(rand_int)

l=['html','css','javascrpit','python','mysql']
rand_choice=np.random.choice(1, 2)
print(rand_choice)

arr = np.array([[1, 2], [4, 5],[6, 7],[8, 7],[1, 2],[4, 5]])
print(arr.shape)

reshaped = arr.reshape(2,6)
print(reshaped)

transposed=arr.T
print(transposed)

arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

import numpy as np
matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[0])
print(matrix[2,2])
print(matrix[1,0])
print(matrix[0,0])
print(matrix[0:3,0])
print(matrix[1:3,1])
print(matrix[0:2,0:2])

arr = np.array([4, 9, 16, 25, 36])

print(arr+1)
print(arr*2)
print(arr**0.5)

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

a=np.array([1,2,3,4,5])
print(np.mean(a))
print(np.var(a))
print(np.std(a))

print(np.min(arr))
print(np.max(arr))

arr = np.array([1,2,3,4,5])
print(np.cumsum(arr)) #[1,3,6,10,15]
print(np.cumprod(arr)) #[1,2,6,24,120]



arr = np.array([1,2,3,4,5,5,6,6,7,8,8,3])
print(arr%2==0)
print(arr[arr%2==0])

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
sorted_arr = np.sort(arr)
print(sorted_arr)

unique_vals=np.unique(arr)
print(unique_vals)

arr = np.array([10, 20, 30])
view_arr = arr.view()
view_arr[0] = 100
print(arr,view_arr)
copy_arr = arr.copy()
copy_arr[0] = 200
print(arr,copy_arr)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))

print(np.linalg.inv(A))

eigenvalues,eigenvectors=np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))
print(vertical_stack)
print(horizontal_stack)

split_arr = np.split(np.array([1, 2, 3, 4, 5, 6]), 6)
print(split_arr)