# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3s9k2jwAGzXRqV0TapAI7uUnWyVZftK
"""

import pandas as pd

prices=[2999, 15999, 52999, 4999, 1999]
products=["Wireless Earbuds", "Smartphone", "Laptop", "Smartwatch", "Bluetooth Speaker"]

product_prices = pd.Series(prices,index=products)
print(product_prices)

print("Mean:", product_prices.mean())
print("Sum:", product_prices.sum())
print("Max:", product_prices.max())
print("Min:", product_prices.min())

print("Head (First 3 Elements):\n", product_prices.head(3))
print("Tail (Last 2 Elements):\n", product_prices.tail(2))

print("Head (First 3 Elements):\n", product_prices.head(3))
print("Tail (Last 2 Elements):\n", product_prices.tail(2))

print("Apply (Adding 18% GST):\n", product_prices.apply(lambda x: f'₹{x*0.18}'))
print("Map(Formatting as Currency):\n", product_prices.map(lambda x: f'₹{x*0.18}'))

print(product_prices.sort_values())

print(product_prices.sort_index())

print(product_prices.sort_index(ascending=False))

print("Value Counts:\n", product_prices.value_counts())