# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WahwO2UwpimUM4F3-_qxy7oibqQCnBb_
"""

import numpy as np
arr1=np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end='\n\n')

arr2=np.array([[1,2,3],[4,5,6]])
print("2-dim",arr2,sep='\n',end='\n\n')

arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("multi-dim",arr3,sep='\n',end='\n\n')

zeros = np.zeros((3,4))
print(zeros)
ones = np.ones((3,4))
print(ones)
identity = np.eye(4)
print(identity)
full_array = np.full((10, 2), 'Booked')
print(full_array)

range_arr= np.arange(10,0,-1)
print(range_arr)

lin_space = np.linspace(50, 100, 6)
print(lin_space)

np.random.seed(10)
rand_arr=np.random.randint(6)
print(rand_arr)