# -*- coding: utf-8 -*-
"""webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FiBHngZDGDJTndTRpfSAmO9v1uHHbYi
"""

# Loading required libraries
import requests
from bs4 import BeautifulSoup

URL = 'https://codegnan.com/'

# Loading the WebPage in Memory using requests library
page = requests.get(URL)

# Check the Status Code of the Page
page.status_code

htmlCode = page.text
print(htmlCode)

soup = BeautifulSoup(htmlCode, 'html.parser')
print(soup)

title = soup.title.text

print("Website Title:", title)

headings = soup.find_all("h3")

for heading in headings:
    print(heading.text.strip())

links = soup.find_all("a")

for link in links[:10]:   # First 10 links
    print(link.get("href"))

images = soup.find_all("img")

for image in images[:5]:
    print(image.get("src"))

description = soup.find("meta", attrs={"name": "description"})

if description:
    print("Description:")
    print(description.get("content"))

for tag in soup.find_all():
    if tag.get("class"):
        print(tag.get("class"))

scripts = soup.find_all("script")

for script in scripts:
    print(script.get("src"))

print(len(soup.find_all("script")))

logo = soup.find("img")

print(logo.get("src"))

og_image = soup.find("meta", property="og:image")

print(og_image["content"])

og_title = soup.find("meta", property="og:title")

print(og_title["content"])

meta_tags = soup.find_all("meta")

for tag in meta_tags:
    print(tag)

paragraphs = soup.find_all("p")

for p in paragraphs[:10]:
    print(p.text.strip())

buttons = soup.find_all("button")

for button in buttons:
    print(button.text.strip())

images = soup.find_all("img")

for image in images[:10]:
    print(image.get("alt"))

print(soup.html["lang"])