# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3s9k2jwAGzXRqV0TapAI7uUnWyVZftK
"""

import pandas as pd

prices=[2999, 15999, 52999, 4999, 1999]
products=["Wireless Earbuds", "Smartphone", "Laptop", "Smartwatch", "Bluetooth Speaker"]

product_prices = pd.Series(prices,index=products)
print(product_prices)

print("Mean:", product_prices.mean())
print("Sum:", product_prices.sum())
print("Max:", product_prices.max())
print("Min:", product_prices.min())

print("Head (First 3 Elements):\n", product_prices.head(3))
print("Tail (Last 2 Elements):\n", product_prices.tail(2))

print("Head (First 3 Elements):\n", product_prices.head(3))
print("Tail (Last 2 Elements):\n", product_prices.tail(2))

print("Apply (Adding 18% GST):\n", product_prices.apply(lambda x: f'₹{x*0.18}'))
print("Map(Formatting as Currency):\n", product_prices.map(lambda x: f'₹{x*0.18}'))

print(product_prices.sort_values())

print(product_prices.sort_index())

print(product_prices.sort_index(ascending=False))

print("Value Counts:\n", product_prices.value_counts())

import pandas as pd
data = {
"Product":["Wireless Earbuds", "Smartphone", "Laptop","Smartwatch", "Bluetooth Speaker"],
"Brand":["SoundMax", "TechNova", "ByteCore", "TimeTrack", "EchoBoom"],
"Price":[2999, 15999, 52999, 4999, 5678],
"Stock": [50, 30, 20, 40, 60],
"BestSeller" :[True,False,False,True,True]
}
df = pd.DataFrame(data)
print(df)

print(df.shape)
print(df.columns)
print(df.info())

from google.colab  import files
import pandas as pd

uploaded = files.upload()

df = pd.read_excel("products_50_rows.xlsx")
print(df)

print(df.head(3))
print(df.tail(2))

print(df.iloc[3])
print(df.iloc[47])
print(df['Product'])
print(df[['Brand', 'Stock']])

import matplotlib.pyplot as plt
hours=[1,2,3,4,5,6,7,8]
visitors=[50,60,65,70,90,120,110,130]
plt.plot(hours,visitors,
         color="blue",
         marker="d",
         linestyle="--",
         alpha=1,
         label="visitors")
plt.title("Website Visitors Per Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Visitors")
plt.legend()
plt.grid(True,linestyle=":",alpha=1)
plt.show()

import matplotlib.pyplot as plt
products=["Laptop","Mobile","Tablet","Headphones","Smartwatch"]
sales=[250,400,150,300,100]
plt.bar(products,sales,color="blue",edgecolor="yellow",alpha=0.5,width=0.5)
plt.title("Product Sales Comparision")
plt.xlabel("Products")
plt.ylabel("Units sold")
plt.show()

import matplotlib.pyplot as plt
marks=[45,55,68,72,68,80,90,55,67,70,
       85,40,60,75,78,82,95,50,62,65,
       58,73,77,63,71,88,92,55,63,59]
plt.hist(marks,bins=10,histtype='bar',color='red',edgecolor='black',density=False)
plt.title("Distribution of Student Marks")
plt.xlabel("Marks Range")
plt.ylabel("Number of Students")
plt.show()

import matplotlib.pyplot as plt
brands=['Apple','Samsung','Xiaomi','Oppo','Others']
market_share=[30,25,20,10,15]
plt.pie(market_share,
        labels=brands,
        autopct="%2f%%",
        startangle=90,
        colors=['gold','skyblue','lightcoral','lightgreen','violet'],
        explode=[0.1,0,0,0,0],
        shadow=True)
plt.title("Mobile Market Share 2025")
plt.show()

import matplotlib.pyplot as plt

scores = [
    [ 70, 85, 90, 92, 88, 76, 95,9],
    [65, 70, 68, 72, 75, 80, 85, 78],
    [90, 92, 94, 96, 88, 91, 89, 93],
    [62, 60, 61, 90, 65, 63, 67, 61],
    [70, 85, 8, 50, 92, 91, 100, 89]
]
plt.boxplot(scores,
            patch_artist=True,
            medianprops=dict(color="red", linewidth=2),
            whiskerprops=dict(color="green"),
            capprops=dict(color="black"),
            notch=False,
            vert=False,
            labels=["A", "B", "C", "D", "E"])

plt.title("Exam Scores Distribution Across Classes")
plt.xlabel("Classes")
plt.ylabel("Scores")
plt.grid(True, linestyle="--", alpha=0.7)

plt.show()

import matplotlib.pyplot as plt

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
visitors = [120, 150, 170, 200, 180, 220, 250]

plt.fill_between(days, visitors,
                 color="skyblue", alpha=0.5,
                 label="Website Visitors")

plt.plot(days, visitors, color="blue", linewidth=1)
plt.title("Website Visitors Over a Week")
plt.xlabel("Day of Week")
plt.ylabel("Number of Visitors")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

data = np.array([
    [30, 32, 31, 29, 28, 27, 26],
    [33, 34, 32, 30, 29, 28, 27],
    [35, 36, 34, 33, 31, 30, 29],
    [37, 38, 35, 34, 32, 31, 30],
    [36, 37, 34, 32, 31, 30, 29]
])

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

weeks = ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5"]

sns.heatmap(data,
            annot=True,
            fmt=".2f",
            cmap="YlOrRd",
            linewidths=0.5,
            xticklabels=days,
            yticklabels=weeks)

plt.title("Weekly Temperature Heatmap", fontsize=14, fontweight="bold")
plt.xlabel("Days of the Week")
plt.ylabel("Weeks")
plt.show()

import matplotlib.pyplot as plt

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
sales = [120, 135, 150, 160, 170, 200, 220]
profit = [30, 40, 45, 50, 55, 70, 80]

plt.figure(figsize=(10, 8))

plt.subplot(2, 2, 1)
plt.plot(days, sales, marker="o", color="blue")
plt.title("Sales Over Days")
plt.grid(True)

plt.subplot(2, 2, 2)
plt.bar(days, sales, color="orange")
plt.title("Sales Bar Chart")

plt.subplot(2, 2, 3)
plt.scatter(sales, profit, color="green", s=100, edgecolors="black")
plt.title("Sales vs Profit")

plt.subplot(2, 2, 4)
plt.pie(sales, labels=days, autopct="%1.1f%%", startangle=90)
plt.title("Sales Distribution")

plt.tight_layout()
plt.show()